### ISSUE TITLE
Pip install from requirements.txt and version

### ISSUE THREAD

**Issue by TAnas0** [mandx/haystack-rqueue#5]
Hi,

I have noticed this bug in the package.
I installed the package the recommended way in the README.md using this command: `pip install http://github.com/mandx/haystack-rqueue/tarball/master`.
This leads to the following result of `pip freeze`:
```
...
Django==1.11.7
django-haystack==2.6.1
django-haystack-rqueue==0.2a0
django-rq==0.9.6
packaging==16.8
...
```
Given a `requirements.txt` file that contains the above lines, the command `pip install -r requirements.txt` throws the error message:
```
Requirement already satisfied: django-haystack==2.6.1 in /data/lib/python3.6/site-packages (from -r requirements.txt (line 21))
Collecting django-haystack-rqueue==0.2a0 (from -r requirements.txt (line 22))
Could not find a version that satisfies the requirement django-haystack-rqueue==0.2a0 (from -r requirements.txt (line 22)) (from versions: )
No matching distribution found for django-haystack-rqueue==0.2a0 (from -r requirements.txt (line 22))
```
I know that installing packages with `pip` directly from GitHub brings some troubles, but I think the version is erroneous.

**Comment by mandx** [comment]
The main reason for `pip` not finding `django-haystack-rqueue==0.2a0` is because this package is not published  to [PyPI](http://pypi.python.org/). If you replace that line in your `requirements.txt` with just `http://github.com/mandx/haystack-rqueue/tarball/master` (the same argument you passed to `pip install`) it should work. (I think the `master` can be replaced with some other branch name or git tag, and it should also work).

Don't know about the version, though. If you look at the `setup.py`, the version number is different, maybe pip/setuptools is transforming the version number into a more "compact" format.

In any case, keep in mind that while I used this package in production environments, it was a while ago since the last time I actually worked with it; I'm not sure if this still work with all the newer versions of Django, Haystack and RQ...
